"""empty message

Revision ID: 097384fe91b1
Revises: 
Create Date: 2022-03-13 18:43:34.878939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097384fe91b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ord_id', sa.String(length=20), nullable=True),
    sa.Column('ord_dt', sa.String(length=20), nullable=True),
    sa.Column('qt_ordd', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('was_rainy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('customer_order_line')
    op.drop_table('customer_order')
    # ### end Alembic commands ###
